Generate extra xbox files
superg/redumper pull request #198
Opened 2024-11-16 15:20 UTC by Deterous

This PR generates the DMI/PFI/SS files that redump.org and abgx360 care about. The functionality is gated behind a `--generate-extra-xbox` option, so these derivative files are not generated by default.
- `{image_name}.dmi` is made by trimming the 4-byte scsi header from `{image_name}.manufacturer`
- `{image_name}.pfi` is made by trimming the 4-byte scsi header from `{image_name}.physical`
- `{image_name}.ss` is made by cleaning the `{image_name}.security` file with the same method that ss_sector_range uses
Additionally, the sector ranges are logged when this occurs.

I initially wanted to put this functionality inside `redumper split` however `split` only runs for CD dumps, and trying to hack it to run for Xbox dumps results in messy code.
I also wanted to put the DMI/PFI/SS hashes and sector range printing into `redumper info` however the `info` step only reads from the main dump (ISO), and hacking it to read from the auxiliary files again results in messy code.
So, the way I've done it is the cleanest way I could come up with.

2024-11-24 13:05 UTC, Deterous commented
Alternatively, if you think these files aren't within scope of Redumper, this can be removed/altered.
Instead outputting these derivative files can be within scope of MPF and the like (ss_sector_range)

2025-01-19 20:56 UTC, superg commented
I briefly looked over it. Fundamentally this is a useful change but DVD dump code is already overloaded, I don't want to complicate it even more. Instead of adapting CD split code to support DVD, it should be defined in a separate function for DVD.

Check how I handle for example "dump" for CD/DVD:
https://github.com/superg/redumper/blob/main/redumper.ixx#L84

Basically what you have to do is to rename CD redumper_split() to redumper_split_cd(), define a new function redumper_split() in redumper.ixx that will conditionally call it if cd profile and define a new redumper_split_dvd() function in a new file dvd/dvd_split.ixx. Finally, just add "split" to default do it all dvd commands in https://github.com/superg/redumper/blob/main/redumper.ixx#L216

Doing it in a separate command will align it better conceptually to CD dumping. Another benefit is that drive presense is not required for this operation as all 3 files will be generated from the dump files (.manufacturer, .physical and .security). 
Check redumper_info() logic as an example, it's easier to understand vs redumper_split(). Basically "if .manufacturer file exists, generate dmi" etc.

Let me know if something is unclear, we can discuss it over Discord.

2025-01-20 07:48 UTC, Deterous commented
Hopefully that's how you had intended it to be added as dvd_split
I have also added a quick error count check in DVD split that should solve #118 
I have not yet tested these changes.

2025-01-20 22:51 UTC, superg requested changes

2025-01-20 22:51 UTC, superg commented on dvd/dvd_dump.ixx
> +    errors.scsi = 0;
This line is not needed as previous = {} clears the structure

2025-01-20 22:51 UTC, superg commented on dvd/dvd_split.ixx
> +    if(options.generate_extra_xbox)
This is misleading, .dmi and .pfi files can be generated for any DVD disc, not just xbox.

Please move out dmi/pfi out of generate_extra_xbox() function here so it's more clear.

Also let's remove --generate-extra-xbox option and generate everything by default. This way dmi and pfi will always be available and ss only if security file exists.

2025-01-20 22:51 UTC, superg commented on dvd/dvd_split.ixx
> +    // std::filesystem::path state_path(image_prefix + ".state");
In general, commented out code like this should be removed unless it's intended to be enabled in near future to add some missing / unknown functionality or shows some important alternative approach.

2025-01-20 22:51 UTC, superg commented on dvd/dvd_split.ixx
> +        throw_line("{} scsi errors detected, unable to continue (use --force-split to ignore)", ctx.dump_errors->scsi);
Please remove "(use --force-split to ignore)", let's not give user hints and tutorials about command line options, this definitely doesn't belong to redumper error output and if it's needed, it should be done elsewhere (documentation / wiki / etc).

2025-01-21 02:44 UTC, Deterous commented on dvd/dvd_split.ixx
> +    if(options.generate_extra_xbox)
.manufacturer and .physical already contain all the DMI/PFI info, the only reason I'm generating DMI/PFI is because the xbox scene has a standard DMI/PFI hash that does not include the scsi header. Is there any other reason to generate DMI/PFI files (that are identical in contents to .manufacturer/.physical)?

2025-01-21 02:46 UTC, Deterous commented on dvd/dvd_split.ixx
> +    // std::filesystem::path state_path(image_prefix + ".state");
I assume there is some future iso/state file checking that can be done for a "dvd split" phase. All I've implemented so far is just a scsi error count. I can remove the comments if it's cleaner.

2025-01-21 02:48 UTC, superg commented on dvd/dvd_split.ixx
> +    if(options.generate_extra_xbox)
I recall somebody complained about not having those specific files for ordinary DVD's. I don't remember the purpose of that though.

2025-01-21 02:50 UTC, superg commented on dvd/dvd_split.ixx
> +    // std::filesystem::path state_path(image_prefix + ".state");
Yes please, we can always add that code later if needed.

2025-01-21 02:56 UTC, Deterous commented on dvd/dvd_split.ixx
> +    if(options.generate_extra_xbox)
Perhaps there is something that redumper could do for DVDs that have non-zeroed .manufacturer, or unusual/unexpected .physical files, but that seems out of scope.
The "DMI/PFI/SS" files that I am creating are specific to how redump and other projects preserve xbox discs.

2025-01-21 04:40 UTC, Deterous commented
Latest commit should fix your issues and has been tested with a Kreon dump. DMI/PFI/SS files successfully generated, and the split step prints the sector ranges that redump needs for submission 👍 
```
*** SPLIT

security sector ranges:
  290332-294427
  521466-525561
  677950-682045
  837486-841581
  986626-990721
  1143286-1147381
  1294684-1298779
  1606598-1610693
  1986112-1990207
  2291938-2296033
  2450818-2454913
  2755770-2759865
  2914704-2918799
  3067104-3071199
  3218968-3223063
  3453126-3457221
  ```

2025-01-21 23:19 UTC, superg approved these changes
LGTM

2025-01-21 23:19 UTC, merged